### ISSUE TITLE
Do you have encountered model datetime field is Time not ActiveSupport::TimeWithZone < Object

### ISSUE THREAD

**Issue by villins** [lighthouse-labs/sinatra-skeleton#8]
```
Show.last.show_time.class
D, [2016-06-14T18:39:14.570142 #4094] DEBUG -- :   Show Load (0.5ms)  SELECT  `shows`.* FROM `shows`  ORDER BY `shows`.`id` DESC LIMIT 1
=> Time
```

**Comment by interlock** [comment]
Does this appear to be a skeleton configuration/dependency issue? Otherwise it may better belong in the ActiveRecord issues: https://github.com/rails/rails/tree/master/activerecord

**Comment by villins** [comment]
@interlock Thank you for your reply, I just want to know whether you had met it. 😊

**Comment by interlock** [comment]
No one here has met that error. Sorry :-(
